apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos-noresource-deployment
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: centos:8
        command: [ "sleep", "3600000" ]